name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Add SSH Key
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
        chmod 400 private_key.pem

    - name: Copy files to EC2
      run: |
        rsync -avz -e "ssh -o StrictHostKeyChecking=no -i private_key.pem" ./ ubuntu@${{ secrets.EC2_PUBLIC_IP }}:/home/ubuntu/app/

        
    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -o ServerAliveCountMax=120 -i private_key.pem ubuntu@${{ secrets.EC2_PUBLIC_IP }} bash -s << 'ENDSSH'
          cd /home/ubuntu/app
          echo "${{ secrets.REACT_ENV_FILE }}" > .env
          docker build -t react-app .
          docker stop react-app || true
          docker rm react-app || true
          docker run -d -p 80:80 --name react-app react-app
        ENDSSH
