name: Deploy to Development EC2

on:
  push:
    branches: [pre-development]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add SSH Key
        run: |
          echo "${{ secrets.EC2_DEV_SSH_KEY }}" > private_key.pem
          chmod 400 private_key.pem

      - name: Copy files to EC2 (Development)
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no -i private_key.pem" ./ ubuntu@${{ secrets.EC2_DEV_IP }}:/home/ubuntu/app/

      - name: Deploy to Development EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${{ secrets.EC2_DEV_IP }} bash -s << 'ENDSSH'
            cd /home/ubuntu/app
            echo "${{ secrets.REACT_DEV_ENV_FILE }}" | base64 -d > .env
            docker build --build-arg NGINX_CONFIG=nginx.dev.conf -t react-app-dev .
            docker stop react-app-dev || true
            docker rm react-app-dev || true
            docker run -d -p 80:80 \
              --name react-app-dev react-app-dev
          ENDSSH
